version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True

  frontend:
    build: ../search-movie
    ports:
      - "5173:5173"
    volumes:
      - ../search-movie:/app
      - /app/node_modules
    stdin_open: true
    tty: true

networks:
  mynetwork:
    driver: bridge